#!/usr/bin/env bash
PLUGIN_LIST="plugin-list.zsh"

ZHS_SYNTAX_HIGHLIGHT="zgen load zsh-users/zsh-syntax-highlighting"
ZHS_SYNTAX_HIGHLIGHT_LINE_CONTENT=$(grep "$ZHS_SYNTAX_HIGHLIGHT" "$PLUGIN_LIST")
grep -v "$ZHS_SYNTAX_HIGHLIGHT" "$PLUGIN_LIST" | sort -c 2>/dev/null 1>/dev/null

if [ "$?" != "0" ]; then
	echo 'Sorting $PLUGIN_LIST ...'
	grep -v "$ZHS_SYNTAX_HIGHLIGHT" "$PLUGIN_LIST" | sort -o "$PLUGIN_LIST"
	# Append "zgen load zsh-users/zsh-syntax-highlighting" at the end.
	echo "$ZHS_SYNTAX_HIGHLIGHT_LINE_CONTENT" >> "$PLUGIN_LIST"
	git reset HEAD $PLUGIN_LIST
	echo 'Please commit again!'
	exit 1
fi

TOTAL_LINE=$(wc -l $PLUGIN_LIST | cut -d' ' -f1)
ZHS_SYNTAX_HIGHLIGHT_LINENO=$(grep -nr "$ZHS_SYNTAX_HIGHLIGHT" "$PLUGIN_LIST" | cut -d':' -f2)

if [ "$ZHS_SYNTAX_HIGHLIGHT_LINENO" != "$TOTAL_LINE" ]; then
	echo 'zsh-users/zsh-syntax-highlighting must be loaded at the end.'
	grep -v "$ZHS_SYNTAX_HIGHLIGHT" "$PLUGIN_LIST" | tee "$PLUGIN_LIST" 1>/dev/null
	# Append "zgen load zsh-users/zsh-syntax-highlighting" at the end.
	echo "$ZHS_SYNTAX_HIGHLIGHT_LINE_CONTENT" >> "$PLUGIN_LIST"
	git reset HEAD $PLUGIN_LIST
	echo 'Please commit again!'
	exit 1
fi
